# Generated by Django 3.2.5 on 2023-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitter', '0002_dweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
    ]
